FROM ubuntu:focal

LABEL org.opencontainers.image.authors="Badr @pythops, Milan @milantodorovic"

ENV TZ=Etc/UTC \
    DEBIAN_FRONTEND=noninteractive

# Install systemd
RUN apt update && apt install -y systemd

# Update apt mirrors
RUN echo "deb http://ports.ubuntu.com/ubuntu-ports/ bionic main" >> /etc/apt/sources.list && \
    apt update

# Nvidia required packages
RUN apt install -y \
        libgles2 \
        libpangoft2-1.0-0 \
        libxkbcommon0 \
        libwayland-egl1 \
        libwayland-cursor0 \
        libunwind8 \
        libasound2 \
        libpixman-1-0 \
        libjpeg-turbo8 \
        libinput10 \
        libcairo2 \
        device-tree-compiler \
        iso-codes \
        libffi6 \
        libncursesw5 \
        libdrm-common \
        libdrm2 \
        libegl-mesa0 \
        libegl1 \
        libegl1-mesa \
        libgtk-3-0 \
        python2 \
        python-is-python2 \
        libgstreamer1.0-0 \
        libgstreamer-plugins-bad1.0-0 \
        i2c-tools \
        bridge-utils

# Additional tools
RUN apt install -y \
        bash-completion \
        build-essential \
        btrfs-progs \
        ca-certificates \
        cmake \
        cron \
        curl \
        dnsutils \
        gnupg2 \
        htop \
        iotop \
        isc-dhcp-client \
        iputils-ping \
        kmod \
        linux-firmware \
        locales \
        net-tools \
        netplan.io \
        pciutils \
        python3-dev \
        samba \
        ssh \
        sudo \
        udev \
        unzip \
        usbutils \
        neovim \
        wpasupplicant \
        parted \
        gdisk \
        e2fsprogs \
        mtd-utils

# Add Nvidia specific repos
RUN curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
RUN apt update

# Nvidia containers
RUN apt install -y \
        docker.io \
        docker-compose-v2 \
        libnvidia-container-tools \
        libnvidia-container1:arm64 \
        nvidia-container-toolkit-base \
        nvidia-container-toolkit \
        nvidia-docker2 \
        mergerfs

# Configure Docker file with Nvidia's parameters
RUN nvidia-ctk runtime configure --runtime=docker

# Nvidias accelerated Gstreamer for video conversion
RUN apt-get install -y \
        gstreamer1.0-tools \
        gstreamer1.0-alsa \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-base-apps \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-libav

RUN wget -q https://github.com/pythops/tegratop/releases/latest/download/tegratop-linux-arm64 -O /usr/local/bin/tegratop && \
    chmod +x /usr/local/bin/tegratop

# Resize the rootfs
COPY scripts/resizerootfs.sh /usr/local/bin
COPY scripts/resizerootfs.service /lib/systemd/system

# Generate locales
RUN locale-gen en_US.UTF-8

# Network configuration
COPY config/netcfg.yaml /etc/netplan/netcfg.yaml

# Seems to loose wifi from time to time, this reconnects automatically and logs the incident
COPY scripts/check_wifi.sh /home
chmod +x /usr/local/bin/check_wifi.sh

# Script for updating docker containers automatically
COPY scripts/update_containers.sh /home
chmod +x /home/update_containers.sh

# Set up cron jobs
crontab -l > tmp_cron
# Update weekly
echo "0 0 * * 0 /home/update_containers.sh" >> tmp_cron
# Check every minute
echo "* * * * * /home/check_wifi.sh" >> tmp_cron
crontab tmp_cron
rm tmp_cron

# Enable services at startuo
RUN systemctl enable resizerootfs.service && \
    systemctl enable systemd-timesyncd

# New user
# username: jetson
# password: jetson
RUN useradd \
        --create-home \
        -G sudo,video,audio \
        -p $(openssl passwd -6 jetson) \
        -s /bin/bash \
        jetson

# Create log file for the WiFi check service
RUN touch /home/jetson/wifi_check_log.txt

# Create a swapfile because this image will always run off of a SSD attached via USB
RUN fallocate -l "4G" "/mnt/swapfile" && \
    cd /mnt/ && \
    chmod 600 swapfile && \
    mkswap swapfile && \
    swapon swapfile && \
    sh -c 'echo "/mnt/swapfile swap swap defaults 0 0" >> /etc/fstab'

# Disable the ZRAM config as we will use ZSWAP in the extlinux parameters
RUN systemctl disable nvzramconfig

# Limit the number of log files from journald
RUN sudo sed -i 's/#SystemMaxFiles=100/SystemMaxFiles=10' /etc/systemd/journald.conf

# Configure and run Samba
RUN (echo "jetson"; echo "jetson") | smbpasswd -s -a jetson
RUN echo "[JETSON_SERVARR]\ncomment = Shared mergerfs drives\npath = /mnt/servarr\nvalid users = jetson\nbrowseable = yes\nwritable = yes\nread only = no\n#guest ok = no" >> /etc/samba/smb.conf
RUN systemctl start smbd

# Add /usr/local/cuda/bin to the PATH
RUN echo "if [ -d \"/usr/local/cuda/bin\" ] ; then" >> /home/jetson/.profile  && \
    echo "  PATH=\"/usr/local/cuda/bin:\$PATH\"" >> /home/jetson/.profile  && \
    echo "fi" >> /home/jetson/.profile
